[tool.poetry]
name = "dilife"
version = "0.1.0"
description = ""
authors = ["Mateus Ribeiro <mateus.ribe.sva@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
uvicorn = "^0.24.0.post1"
pydantic = {extras = ["email"], version = "^2.5.1"}
sqlalchemy = "^2.0.23"
pydantic-settings = "^2.1.0"
alembic = "^1.12.1"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.6"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
taskipy = "^1.12.0"
blue = "^0.9.1"
ruff = "^0.1.5"
httpx = "^0.25.1"
isort = "^5.12.0"
factory-boy = "^3.3.0"
freezegun = "^1.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100
exclude = ['.venv', 'migrations']

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
extend_skip = ['migrations']

[tool.pytest.ini_options]
pythonpath = "."

[tool.blue]
extend-exclude = "(migrations/)"

[tool.taskipy.tasks]
lint = "ruff . && blue --check . --diff"
format = "isort . && blue ."
run = "uvicorn dilife.app:app --reload"
pre_test = "task format && task lint"
test = "pytest -s -x --cov=dilife -vv"
post_test = "coverage html"
